# SPDX-FileCopyrightText: The terraform-provider-migadu Authors
# SPDX-License-Identifier: 0BSD

version: 2
updates:
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: daily
    assignees:
      - sebhoss
